const fs = require('fs');

// Vercel will inject these securely during the Build phase
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_KEY || '';

// Write them into a static config.js file which is ignored by Git
const content = `
// Auto-generated by Vercel Build Step. DO NOT commit to GitHub.
window.ENV = {
    SUPABASE_URL: "${supabaseUrl}",
    SUPABASE_KEY: "${supabaseKey}"
};
`;

try {
    fs.writeFileSync('config.js', content.trim());
    console.log('✅ config.js successfully generated by Vercel Build!');
} catch (err) {
    console.error('❌ Error generating config.js:', err);
    process.exit(1);
}
